# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'AniwaysExampleProject' do

pod 'Aniways'
pod 'JSQMessagesViewController', :git => 'https://github.com/Aniways/JSQMessagesViewController', :branch => 'with-aniways'

end
